# connect timeout in seconds
connect_timeout=30
# network timeout in seconds
network_timeout=60
# the base path to store log files
base_path=/fastdfs_data_and_log/client
# tracker_server
tracker_server=172.30.0.3:22122
# standard log level
log_level=info
# if use connection pool
use_connection_pool = false
# connections whose the idle time exceeds this time will be closed
connection_pool_max_idle_time = 3600
# if load FastDFS parameters from tracker server
load_fdfs_parameters_from_tracker=false
# if use storage ID instead of IP address
use_storage_id = false
# specify storage ids filename, can use relative or absolute path
storage_ids_filename = storage_ids.conf
# HTTP settings
http.tracker_server_port=80
