# is this config file disabled
disabled=false
# the name of the group this storage server belongs to
group_name=group1
# bind_addr
bind_addr=
# if bind an address of this host when connect to other servers
client_bind=true
# the storage server port
port=23000
# connect timeout
connect_timeout=30
# network timeout
network_timeout=60
# heart beat interval
heart_beat_interval=30
# stat report interval
stat_report_interval=60
# the base path to store data and log files
base_path=/fastdfs_data_and_log/storage
# max concurrent connections the server supported
max_connections=256
# the buff size to recv / send data
buff_size = 256KB
# accept thread count
accept_threads=1
# work thread count
work_threads=4
# if disk read / write separated
disk_rw_separated = true
# disk reader thread count per store base path
disk_reader_threads = 1
# disk writer thread count per store base path
disk_writer_threads = 1
# when no entry to sync, try read binlog again after X milliseconds
sync_wait_msec=50
# after sync a file, usleep milliseconds
sync_interval=0
# storage sync start time of a day
sync_start_time=00:00
# storage sync end time of a day
sync_end_time=23:59
# write to the mark file after sync N files
write_mark_file_freq=500
# store_path count, default value is 1
store_path_count=1
# store_path#, based 0, if store_path0 not exists, it's value is base_path
store_path0=/fastdfs_data_and_log/storage
# subdir_count * subdir_count directories will be auto created under each
subdir_count_per_path=256
# tracker_server can occur more than once
tracker_server=172.30.0.3:22122
# standard log level
log_level=info
# unix group name
run_by_group=
# unix username
run_by_user=
# allow_hosts
allow_hosts=*
# the mode of the files distributed to the data path
file_distribute_path_mode=0
# valid when file_distribute_to_path is set to 0 (round robin)
file_distribute_rotate_count=100
# FileID is composed as: {store_path_index}{subdir_count}{filename}
fsync_after_written_bytes=0
# sync log buff to disk every interval seconds
sync_log_buff_interval=10
# thread stack size, should >= 512KB
thread_stack_size=512KB
# the priority as a source server for uploading file.
upload_priority=10
# the NIC alias prefix
if_alias_prefix=
# if check file duplicate, when set to true, use FastDHT to store file indexes
check_file_duplicate=0
# file signature method for check file duplicate
file_signature_method=hash
# namespace for storing file indexes (key-value pairs)
key_namespace=FastDFS
# set keep_alive to 1 to enable persistent connection
keep_alive=0
# if log to access log
use_access_log = false
# if rotate the access log every day
rotate_access_log = false
# rotate access log time base
access_log_rotate_time=00:00
# if rotate the error log every day
rotate_error_log = false
# rotate error log time base
error_log_rotate_time=00:00
# rotate error log when the log file exceeds this size
rotate_error_log_size = 0
# keep days of the log files
log_file_keep_days = 0
# if skip the invalid record when sync file
file_sync_skip_invalid_record=false
# if use connection pool
use_connection_pool = false
# connections whose the idle time exceeds this time will be closed
connection_pool_max_idle_time = 3600
# HTTP port
http.server_port=8888
# the domains of the storage server web server
http.domain_name=
# use "#include" directive to include HTTP other settiongs
# NOTE: must use double quote to include filename
